# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty
relative_permalinks: true

# Setup
title:            "E.J. Finneran"
description:      'I work with Ruby & Go among other things at <a href="https://www.cloudability.com">Cloudability.</a> I’m the author of the <a href="https://github.com/ejfinneran/ratelimit">Ratelimit Gem</a> and I love a good IPA.'

url:              http://finneran.us
baseurl:          /

author:
  name:           'E.J. Finneran'
  url:            https://twitter.com/ejfinneran

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/ejfinneran/ejfinneran.github.com
